name:         ccp4
version:      0.0.0
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  CCP4 density map file reader
homepage:     https://github.com/hermanbergwerf/ccp4
environment:
  sdk:        '>=1.8.0 <2.0.0'
dev_dependencies:
  test:       ^0.12.23